# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

services:
  service__varnish:
    image: arm64v8/varnish:latest
    volumes:
      - ./data/varnish/default.vcl:/etc/varnish/default.vcl:ro
    restart: unless-stopped
    ports:
      - 127.0.0.1:1002:80
    environment:
      VARNISH_SIZE: 1G
    cpus: "0.25"
    mem_limit: "256M"
    depends_on:
      - app__url_shortener

  service__redis:
    image: arm64v8/redis:latest
    volumes:
      - ./data/redis:/data
    cpus: "0.25"
    mem_limit: "512M"
    restart: unless-stopped

  app__url_shortener:
    build:
      context: .
    environment:
      PORT: 1234
      REDIS_HOST: service__redis
      REDIS_PORT: 6379
      NODE_ENV: production
      APP_URL: l.ramit.io
    cpus: "0.5"
    mem_limit: "256M"
    restart: unless-stopped
    depends_on:
      - service__redis
    develop:
      watch:
        - path: ./src
          action: rebuild
